name: KitPvP
version: ${project.version}
main: cc.fatenetwork.kitpvp.KitPvP
api-version: 1.8.8
authors: [Hackusate_PvP]
website: www.fatenetwork.cc
commands:
  applykit:
    description: Apply your deafult kit
  balance:
    aliases: [bal]
  economy:
    aliases: [eco]
  clan:
    aliases: [clans]
    description: Main comman executor for clans.
  combat:
    aliases: [ct]
    description: Check to see if you are in combat.
  kit:
    description: Main command exector for kits
  kits:
    description: Lists all available kits.
  lunarclient:
    aliases: [lunar, lc]
    description: Get information about the luanr client
  quest:
    aliases: [quests]
    description: View all your quests.
  settings:
    aliases: [profile]
  shop:
  spawn:
  teammate:
  test:
